### ISSUE TITLE
Show pointer when using stylus

### ISSUE THREAD

**Issue by steewbsd** [scrivanolabs/ScrivanoForLinux#8] opened 2022-10-18 10:57 UTC
Hello, app looks great, but currently lacks a very important feature (or it is an issue on my side).
I cannot see any kind of cursor or pointer when drawing with a stylus when using the flatpak version in GNOME Wayland.
My graphics tablet has no screen, so it is very complicated to draw when I can't see the current cursor pointer.
You should consider adding a feature akin to Xournal++'s where you can choose to show a mini pen icon in the cursor or directly showing a dot.
If this is default behavior, I cannot see it in the flatpak.
Thank you.

**Comment by steewbsd** [comment] 2022-10-18 10:59
[Screencast from 2022-10-18 12-53-00.webm](https://user-images.githubusercontent.com/26441684/196411949-b62a551c-cf0f-47c5-ac9d-1d0fa84ec7fb.webm)

Here is a sample of my issue.

**Comment by scrivanolabs** [comment] 2022-10-18 11:41
Hi, thanks for reporting this. This is intended behaviour as I think on touchscreens the cursor is a distraction and hiding it allows a more natural writing experience. However, as you said when using graphics tablets this behaviour can be a little confusing. I think the best thing to do would be either only hide the cursor when using touchscreens or maybe provide an option in the settings for those who want the cursor always visible.

**Comment by thales-maciel** [comment] 2022-11-12 23:18
+1 here. In desktop my cursor is hidden only when I'm writing (wacom tablet). This results in heavy distraction as the cursor blinks every time I lift the pen up

**Comment by scrivanolabs** [comment] 2022-11-16 13:43
The latest beta of Scrivano (v. 0.14.6) now includes an option in settings to address this issue. The beta release is only available on Flathub, you can download it by doing:

1. `flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`
2. `flatpak install flathub-beta com.github.scrivanolabs.scrivano`

This will be merged in the stable release cycle very soon.

**Closed** 2022-12-07 09:04 UTC
